### ISSUE TITLE
Possible to update to modern kernels? 

### ISSUE THREAD

**Issue by rabarbar42** [fabio-d/block-led-trigger#1]
Hi. I don't know how to use the builtin kernel trigger you mention, so I tried your code instead. It won't build on 5.9, the messages upon compilation are:

> ~/programs/block-led-trigger/block-led-trigger-master(0)$ make
> make -C /lib/modules/5.9.0-4-amd64/build M=/home//programs/block-led-trigger/block-led-trigger-master modules
> make[1]: Entering directory '/usr/src/linux-headers-5.9.0-4-amd64'
>   CC [M]  /home//programs/block-led-trigger/block-led-trigger-master/block_led_trigger.o
>   MODPOST /home//programs/block-led-trigger/block-led-trigger-master/Module.symvers
> ERROR: modpost: "blk_lookup_devt" [/home//programs/block-led-trigger/block-led-trigger-master/block_led_trigger.ko] undefined!
> ERROR: modpost: "kallsyms_on_each_symbol" [/home//programs/block-led-trigger/block-led-trigger-master/block_led_trigger.ko] undefined!
> make[3]: *** [/usr/src/linux-headers-5.9.0-4-common/scripts/Makefile.modpost:111: /home//programs/block-led-trigger/block-led-trigger-master/Module.symvers] Error 1
> make[3]: *** Deleting file '/home//programs/block-led-trigger/block-led-trigger-master/Module.symvers'
> make[2]: *** [/usr/src/linux-headers-5.9.0-4-common/Makefile:1709: modules] Error 2
> make[1]: *** [/usr/src/linux-headers-5.9.0-4-common/Makefile:185: __sub-make] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.9.0-4-amd64'
> make: *** [Makefile:18: default] Error 2

**Comment by fabio-d** [comment]
Hi, thank you for reporting!
I have just pushed a new version that should work with current kernels (tested on 5.13.6).
Feel free to reopen this issue if it still fails on your system.

**Comment by karmaking** [comment]
Thanks a lot for updating, works like a charm now! :)

For the record: In self-built kernels (I'm on Gentoo), CONFIG_KALLSYMS_ALL=y must be set, otherwise __tracepoint_block_rq_issue will not be exposed in /proc/kallsyms and build will fail.
